const USERS = Object.freeze({
   SUPER_ADMIN: "SUPER_ADMIN",
   ADMIN: "ADMIN",
   TICKET_MANAGER: "TICKET_MANAGER",
   CUSTOMER: "CUSTOMER"
})

const { SUPER_ADMIN, ADMIN, CUSTOMER, TICKET_MANAGER } = USERS
const ADMIN_RIGHTS_USER = Object.freeze({ USER_RIGHTS: [TICKET_MANAGER, CUSTOMER] });
const SUPER_ADMIN_RIGHTS_USERS = Object.freeze({ USER_RIGHTS: [ADMIN, TICKET_MANAGER, CUSTOMER] });
const TICKET_MANAGER_RIGHTS_USERS = Object.freeze({ USER_RIGHTS: [CUSTOMER] });
const CUSTOMER_RIGHTS_USERS = Object.freeze({ USER_RIGHTS: [CUSTOMER] });

const USER_TYPE = Object.freeze({
   [SUPER_ADMIN]: { type: SUPER_ADMIN, ...SUPER_ADMIN_RIGHTS_USERS },
   [ADMIN]: { type: ADMIN, ...ADMIN_RIGHTS_USER },
   [TICKET_MANAGER]: { type: TICKET_MANAGER, ...TICKET_MANAGER_RIGHTS_USERS },
   [CUSTOMER]: { type: CUSTOMER, ...CUSTOMER_RIGHTS_USERS }
})


module.exports = Object.freeze({
   USER_TYPE, USERS
})